---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hostagei/public_html/
    - /bin/rm -rf $DEPLOYPATH/static
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/rm -f $DEPLOYPATH/asset-manifest.json
    - /bin/rm -f $DEPLOYPATH/manifest.json
    - /bin/rm -f $DEPLOYPATH/robots.txt
    - /bin/rm -f $DEPLOYPATH/favicon.ico
    - /bin/cp -R build/. $DEPLOYPATH